#+TITLE: *Iron Brush Tattoo* /Case Jewelry/
#+DATE: Tue May  3 10:45:24 CDT 2016
#+AUTHOR: AnderSon
#+OPTIONS: tags:nil

/Rails 4.2.6/

https://github.com/IronBrushTattoo/cj_rails.git

* Files

** Gemfile

   [[./Gemfile]]

   #+NAME: Gemfile
   #+begin_src ruby :tangle Gemfile :padline no
     source 'https://rubygems.org'

     gem 'rails', '4.2.6'
     gem 'pg', '~> 0.15'
     gem 'sass-rails', '~> 5.0'
     gem 'uglifier', '>= 1.3.0'
     gem 'coffee-rails', '~> 4.1.0'
     gem 'jquery-rails'
     gem 'turbolinks'
     gem 'jbuilder', '~> 2.0'
     gem 'sdoc', '~> 0.4.0', group: :doc

     group :development, :test do
       gem 'byebug'
     end

     group :development do
       gem 'web-console', '~> 2.0'
       gem 'spring'
     end
   #+end_src




** database.yml

   [[./config/database.yml]]

* First steps :rails_template:rails:rake:

  : rake db:migrate
  : rake db:setup
* Project

  The purpose of this application is produce several pdf files from an xlsx file,
  as a re-implementation of https://github.com/IronBrushTattoo/cj as a web 
  application.

** User Story

   - user logs in
   - chooses xlsx file for upload
   - selects number of days back to make labels from
   - submits
     - BACKGROUND
       - cj-parser.rb does what it does...
         - [ ] rewrite in rails?
   - downloads sheets(pdf files)

** Views

*** Routes

    [[./config/routes.rb]]

    #+NAME: routes.rb
    #+begin_src ruby :tangle config/routes.rb :padline no
      Rails.application.routes.draw do
        root 'pages#home'

        # The priority is based upon order of creation: first created -> highest priority.
        # See how all your routes lay out with "rake routes".

        # You can have the root of your site routed with "root"
        # root 'welcome#index'

        # Example of regular route:
        #   get 'products/:id' => 'catalog#view'

        # Example of named route that can be invoked with purchase_url(id: product.id)
        #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

        # Example resource route (maps HTTP verbs to controller actions automatically):
        #   resources :products

        # Example resource route with options:
        #   resources :products do
        #     member do
        #       get 'short'
        #       post 'toggle'
        #     end
        #
        #     collection do
        #       get 'sold'
        #     end
        #   end

        # Example resource route with sub-resources:
        #   resources :products do
        #     resources :comments, :sales
        #     resource :seller
        #   end

        # Example resource route with more complex sub-resources:
        #   resources :products do
        #     resources :comments
        #     resources :sales do
        #       get 'recent', on: :collection
        #     end
        #   end

        # Example resource route with concerns:
        #   concern :toggleable do
        #     post 'toggle'
        #   end
        #   resources :posts, concerns: :toggleable
        #   resources :photos, concerns: :toggleable

        # Example resource route within a namespace:
        #   namespace :admin do
        #     # Directs /admin/products/* to Admin::ProductsController
        #     # (app/controllers/admin/products_controller.rb)
        #     resources :products
        #   end
      end
    #+end_src

*** Static Pages

    : root 'pages#home'    

    [[Pages]]

**** Home

     [[./app/views/pages/home.html.erb]]

** Controllers

*** Pages

    Static pages controller

    #+begin_src sh
      rails g controller pages --skip-assets
    #+end_src

    #+RESULTS:
    | create | app/controllers/pages_controller.rb       |
    | invoke | erb                                       |
    | create | app/views/pages                           |
    | invoke | test_unit                                 |
    | create | test/controllers/pages_controller_test.rb |
    | invoke | helper                                    |
    | create | app/helpers/pages_helper.rb               |
    | invoke | test_unit                                 |

** TODO

   - [ ] user authentication
   - [ ] file upload
     - [ ] only xlsx file?
   - [ ] file storage
     - [ ] archival api?
   - [ ] 


